### ISSUE TITLE
Inicial Data 

### ISSUE THREAD

**Issue by danieramiz** [smartnsoft/flappy_search_bar#18]
This plugin is very similar to the search box on the google photos page.
But I'm not sure why we don't have a property to charge the initial Data. So the present data since the beginning and then perform some search on that initial Data.

**Comment by hinterlandcreative** [comment]
Use `suggestions` parameter to set initial data before a search is performed.

**Comment by ThomasEcalle** [comment]
Hi @danieramiz  
First of all, I am sorry for the delay.
The situation in my company (in France) with the Covid-19 has forced us to put our open source projects on the side for a moment... But I am back ! :)

Like @hinterlandsupplyco has said, I suggest you to use the `suggestions` field i order to show a first list before any search :)

I'll try to be more present on this package, despite the difficult context that had lead us to change a lot the way we work here, sorry again for the delay :)
