### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by leynier** [smartnsoft/flappy_search_bar#56]
Hi, I could help with this. https://dart.dev/null-safety/migration-guide

**Comment by erperejildo** [comment]
Any update?

**Comment by ShreyasBhaktharam** [comment]
Any update on this? This is the only package in my app that does not support null-safety

**Comment by maxyhi** [comment]
found this branch that seems to work great as well https://pub.dev/packages/flappy_search_bar_ns

**Comment by leynier** [comment]
I'll close this issue because this package seems unmaintained.

Use the fork mentioned above can be an alternative.
